name = "nhanbin/staking-validator-demo"
version = "0.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'nhanbin/staking-validator-demo'"

[repository]
user = "nhanbin"
project = "staking-validator-demo"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
